name: Framework pull request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  framework-PR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodule
      uses: actions/checkout@v3
      with:
        repository: rest-for-physics/framework
        path: framework
        ref: master
    - name: Checkout branch
      run: |
        cd framework
        ./scripts/checkoutRemoteBranch.sh ${{ inputs.branch }}
    - name: Automatic PR on framework at submodule PR
      uses: ./framework/.github/actions/submodulePR
      with:
        branch: ${{ env.BRANCH_NAME }}
        submodule: source/libraries/raw
        token: ${{ secrets.REST_TOKEN }}
